### ISSUE TITLE
[QUESTION] Is MIDI Latency normal?

### ISSUE THREAD

**Issue by Psykrot** [StavWasPlayZ/Genshin-Instruments#19]
I'm using the 1.18.2 Forge version of the mod and I plugged in my MIDI controller. Everything seems to be working, however there is a small delay between pressing the key and the note playing. If I play on my PC keyboard, there is no latency. 

Is this normal? Or is there something I can do to reduce the latency coming from using a MIDI keyboard?

**Comment by StavWasPlayZ** [comment]
Hey there! Sorry to hear this! 

Unfortunately, I don't really have a way to diagnose this issue, even if you were to send your logs... :(

Maybe your PC is low-end? Perhaps you should try closing some background apps?  
Have you tried restarting your computer? (Not turning it off then on) 

If all fails, I'd recommend getting a software like LoopMidi to hopefully instantaneously detect your MIDI, and *then* play it in Minecraft. 

[Attached here is a tutorial for that.](https://www.youtube.com/watch?v=B_rYJnTzIC0)

This is just one of many MIDI loopback softwares, I just happen to be familiar with this the most.

Other than that, I'll be closing this issue—because I really am just unable to help you... This is outside of my capabilities :')

Do keep me posted if you succeed, though :D
