### ISSUE TITLE
[SUGGESTION] Additional instruments.

### ISSUE THREAD

**Issue by chrisizatt** [StavWasPlayZ/Genshin-Instruments#6]
Since I couldn't find a discord, I just wanted to say how much I've enjoyed this mod. It's an incredible idea that I've enjoyed so much in many other games, I'm surprised it took this long for such a good implementation of this feature to come along. Thank you so much for your passionate and hard work with this mod.

The only suggestion I would have is adding more instruments; I would love to play a trumpet or violin or something along with the existing instruments; or maybe it could be a separate addon mod? Regardless, even without that, this mod is just perfect. Thank you again.

**Comment by StavWasPlayZ** [comment]
THANK YOU SO INCREDIBLY MUCHHH 😭😭  
This means so much to me to get such positive feedback and appreciation ♥


# Regarding more instruments
it is something I have well thought of, and actually been preparing for since the release of this mod! However, I plan to keep this mod clean of any additional nonsense, only implementing the core fundamentals of Genshin.  
I thus plan on making a child-mod that will derive from the API I built upon to implement new instruments into the game, along with additional musical features!

This especially goes along with the fact the the latest v3.1 release includes the *absolute final* implementations of the API, so I will feel much less pressured to work on something that might later become deprecated :D

However, continued development on the child project may take (much) longer than expected. Studies are nearing again, and I am very burnt out from constant development on just *this* project.
![image](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/89315181/a2345dc2-5c05-4c4e-abd6-e4851eca769a)


Please don't mind me pinning this post as a reminder for me, and for any who may seek this question in the feature.


> I couldn't find a discord

That's because it ain't my thing 😅

Regardless, hope you enjoy playing, and yet again; thank you so much!

**Comment by StavWasPlayZ** [comment]
# Surprise!!

Even More Instruments is out now!

CurseForge: https://curseforge.com/minecraft/mc-mods/even-more-instruments/  
Modrinth: https://modrinth.com/mod/evenmoreinstruments  
> **NOTE:** They are currently held for review, so they will become available at a later time

Also source code: https://github.com/StavWasPlayZ/Even-More-Instruments/

Enjoy!
